name: gorzow
description: "Gorzow - Twoje miasto, Twój bastion."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.11.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  google_fonts: ^8.0.2
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  geolocator: ^14.0.2
  external_app_launcher: ^4.0.3
  intl: ^0.20.2
  reorderable_grid_view: ^2.2.8
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.5.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icon_gorzow.svg
